/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lifetime extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 1530346963;

	/**
	 * The singleton instance of <code>lifetime</code>
	 */
	public static final Lifetime LIFETIME = new Lifetime();

	/**
	 * No further instances allowed
	 */
	private Lifetime() {
		super("lifetime");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			lifetime.backend.persistence.jooq.tables.Account.ACCOUNT,
			lifetime.backend.persistence.jooq.tables.Address.ADDRESS,
			lifetime.backend.persistence.jooq.tables.Competition.COMPETITION,
			lifetime.backend.persistence.jooq.tables.Course.COURSE,
			lifetime.backend.persistence.jooq.tables.KnowledgeUnit.KNOWLEDGE_UNIT,
			lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT,
			lifetime.backend.persistence.jooq.tables.Lecture.LECTURE,
			lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT,
			lifetime.backend.persistence.jooq.tables.LifetimeOrg.LIFETIME_ORG,
			lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER,
			lifetime.backend.persistence.jooq.tables.Photo.PHOTO,
			lifetime.backend.persistence.jooq.tables.Project.PROJECT,
			lifetime.backend.persistence.jooq.tables.SchemaVersion.SCHEMA_VERSION,
			lifetime.backend.persistence.jooq.tables.Sport.SPORT,
			lifetime.backend.persistence.jooq.tables.Study.STUDY,
			lifetime.backend.persistence.jooq.tables.Task.TASK,
			lifetime.backend.persistence.jooq.tables.Training.TRAINING,
			lifetime.backend.persistence.jooq.tables.Work.WORK,
			lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT);
	}
}
