/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lifetime.backend.persistence.jooq.tables.Account;
import lifetime.backend.persistence.jooq.tables.Address;
import lifetime.backend.persistence.jooq.tables.Competition;
import lifetime.backend.persistence.jooq.tables.Course;
import lifetime.backend.persistence.jooq.tables.KnowHowUnit;
import lifetime.backend.persistence.jooq.tables.KnowledgeUnit;
import lifetime.backend.persistence.jooq.tables.Lecture;
import lifetime.backend.persistence.jooq.tables.LifetimeEvent;
import lifetime.backend.persistence.jooq.tables.LifetimeOrg;
import lifetime.backend.persistence.jooq.tables.LifetimeUser;
import lifetime.backend.persistence.jooq.tables.Photo;
import lifetime.backend.persistence.jooq.tables.Project;
import lifetime.backend.persistence.jooq.tables.SchemaVersion;
import lifetime.backend.persistence.jooq.tables.Sport;
import lifetime.backend.persistence.jooq.tables.Study;
import lifetime.backend.persistence.jooq.tables.Task;
import lifetime.backend.persistence.jooq.tables.Training;
import lifetime.backend.persistence.jooq.tables.Work;
import lifetime.backend.persistence.jooq.tables.WorkUnit;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lifetime extends SchemaImpl {

    private static final long serialVersionUID = 942592627;

    /**
     * The reference instance of <code>lifetime</code>
     */
    public static final Lifetime LIFETIME = new Lifetime();

    /**
     * The table <code>lifetime.account</code>.
     */
    public final Account ACCOUNT = lifetime.backend.persistence.jooq.tables.Account.ACCOUNT;

    /**
     * The table <code>lifetime.address</code>.
     */
    public final Address ADDRESS = lifetime.backend.persistence.jooq.tables.Address.ADDRESS;

    /**
     * The table <code>lifetime.competition</code>.
     */
    public final Competition COMPETITION = lifetime.backend.persistence.jooq.tables.Competition.COMPETITION;

    /**
     * The table <code>lifetime.course</code>.
     */
    public final Course COURSE = lifetime.backend.persistence.jooq.tables.Course.COURSE;

    /**
     * The table <code>lifetime.knowledge_unit</code>.
     */
    public final KnowledgeUnit KNOWLEDGE_UNIT = lifetime.backend.persistence.jooq.tables.KnowledgeUnit.KNOWLEDGE_UNIT;

    /**
     * The table <code>lifetime.know_how_unit</code>.
     */
    public final KnowHowUnit KNOW_HOW_UNIT = lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT;

    /**
     * The table <code>lifetime.lecture</code>.
     */
    public final Lecture LECTURE = lifetime.backend.persistence.jooq.tables.Lecture.LECTURE;

    /**
     * The table <code>lifetime.lifetime_event</code>.
     */
    public final LifetimeEvent LIFETIME_EVENT = lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT;

    /**
     * The table <code>lifetime.lifetime_org</code>.
     */
    public final LifetimeOrg LIFETIME_ORG = lifetime.backend.persistence.jooq.tables.LifetimeOrg.LIFETIME_ORG;

    /**
     * The table <code>lifetime.lifetime_user</code>.
     */
    public final LifetimeUser LIFETIME_USER = lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER;

    /**
     * The table <code>lifetime.photo</code>.
     */
    public final Photo PHOTO = lifetime.backend.persistence.jooq.tables.Photo.PHOTO;

    /**
     * The table <code>lifetime.project</code>.
     */
    public final Project PROJECT = lifetime.backend.persistence.jooq.tables.Project.PROJECT;

    /**
     * The table <code>lifetime.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = lifetime.backend.persistence.jooq.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>lifetime.sport</code>.
     */
    public final Sport SPORT = lifetime.backend.persistence.jooq.tables.Sport.SPORT;

    /**
     * The table <code>lifetime.study</code>.
     */
    public final Study STUDY = lifetime.backend.persistence.jooq.tables.Study.STUDY;

    /**
     * The table <code>lifetime.task</code>.
     */
    public final Task TASK = lifetime.backend.persistence.jooq.tables.Task.TASK;

    /**
     * The table <code>lifetime.training</code>.
     */
    public final Training TRAINING = lifetime.backend.persistence.jooq.tables.Training.TRAINING;

    /**
     * The table <code>lifetime.work</code>.
     */
    public final Work WORK = lifetime.backend.persistence.jooq.tables.Work.WORK;

    /**
     * The table <code>lifetime.work_unit</code>.
     */
    public final WorkUnit WORK_UNIT = lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT;

    /**
     * No further instances allowed
     */
    private Lifetime() {
        super("lifetime", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT,
            Address.ADDRESS,
            Competition.COMPETITION,
            Course.COURSE,
            KnowledgeUnit.KNOWLEDGE_UNIT,
            KnowHowUnit.KNOW_HOW_UNIT,
            Lecture.LECTURE,
            LifetimeEvent.LIFETIME_EVENT,
            LifetimeOrg.LIFETIME_ORG,
            LifetimeUser.LIFETIME_USER,
            Photo.PHOTO,
            Project.PROJECT,
            SchemaVersion.SCHEMA_VERSION,
            Sport.SPORT,
            Study.STUDY,
            Task.TASK,
            Training.TRAINING,
            Work.WORK,
            WorkUnit.WORK_UNIT);
    }
}
