/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in lifetime
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table lifetime.account
	 */
	public static final lifetime.backend.persistence.jooq.tables.Account ACCOUNT = lifetime.backend.persistence.jooq.tables.Account.ACCOUNT;

	/**
	 * The table lifetime.address
	 */
	public static final lifetime.backend.persistence.jooq.tables.Address ADDRESS = lifetime.backend.persistence.jooq.tables.Address.ADDRESS;

	/**
	 * The table lifetime.competition
	 */
	public static final lifetime.backend.persistence.jooq.tables.Competition COMPETITION = lifetime.backend.persistence.jooq.tables.Competition.COMPETITION;

	/**
	 * The table lifetime.course
	 */
	public static final lifetime.backend.persistence.jooq.tables.Course COURSE = lifetime.backend.persistence.jooq.tables.Course.COURSE;

	/**
	 * The table lifetime.lecture
	 */
	public static final lifetime.backend.persistence.jooq.tables.Lecture LECTURE = lifetime.backend.persistence.jooq.tables.Lecture.LECTURE;

	/**
	 * The table lifetime.lifetime_event
	 */
	public static final lifetime.backend.persistence.jooq.tables.LifetimeEvent LIFETIME_EVENT = lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT;

	/**
	 * The table lifetime.lifetime_org
	 */
	public static final lifetime.backend.persistence.jooq.tables.LifetimeOrg LIFETIME_ORG = lifetime.backend.persistence.jooq.tables.LifetimeOrg.LIFETIME_ORG;

	/**
	 * The table lifetime.lifetime_user
	 */
	public static final lifetime.backend.persistence.jooq.tables.LifetimeUser LIFETIME_USER = lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER;

	/**
	 * The table lifetime.photo
	 */
	public static final lifetime.backend.persistence.jooq.tables.Photo PHOTO = lifetime.backend.persistence.jooq.tables.Photo.PHOTO;

	/**
	 * The table lifetime.project
	 */
	public static final lifetime.backend.persistence.jooq.tables.Project PROJECT = lifetime.backend.persistence.jooq.tables.Project.PROJECT;

	/**
	 * The table lifetime.schema_version
	 */
	public static final lifetime.backend.persistence.jooq.tables.SchemaVersion SCHEMA_VERSION = lifetime.backend.persistence.jooq.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table lifetime.sport
	 */
	public static final lifetime.backend.persistence.jooq.tables.Sport SPORT = lifetime.backend.persistence.jooq.tables.Sport.SPORT;

	/**
	 * The table lifetime.study
	 */
	public static final lifetime.backend.persistence.jooq.tables.Study STUDY = lifetime.backend.persistence.jooq.tables.Study.STUDY;

	/**
	 * The table lifetime.task
	 */
	public static final lifetime.backend.persistence.jooq.tables.Task TASK = lifetime.backend.persistence.jooq.tables.Task.TASK;

	/**
	 * The table lifetime.training
	 */
	public static final lifetime.backend.persistence.jooq.tables.Training TRAINING = lifetime.backend.persistence.jooq.tables.Training.TRAINING;

	/**
	 * The table lifetime.work
	 */
	public static final lifetime.backend.persistence.jooq.tables.Work WORK = lifetime.backend.persistence.jooq.tables.Work.WORK;
}
