/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum LifetimeEventStatus implements org.jooq.EnumType {

	CREATED("CREATED"),

	RUNNING("RUNNING"),

	PAUSED("PAUSED"),

	STOPPED("STOPPED"),

	FINISHED("FINISHED");

	private final java.lang.String literal;

	private LifetimeEventStatus(java.lang.String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Schema getSchema() {
		return null;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getName() {
		return "lifetime_event_status";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
