/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.AccountRecord> {

	private static final long serialVersionUID = -1810508982;

	/**
	 * The singleton instance of <code>lifetime.account</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Account ACCOUNT = new lifetime.backend.persistence.jooq.tables.Account();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.AccountRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.AccountRecord.class;
	}

	/**
	 * The column <code>lifetime.account.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AccountRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.account.email</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AccountRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.account.password</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AccountRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>lifetime.account</code> table reference
	 */
	public Account() {
		this("account", null);
	}

	/**
	 * Create an aliased <code>lifetime.account</code> table reference
	 */
	public Account(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Account.ACCOUNT);
	}

	private Account(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.AccountRecord> aliased) {
		this(alias, aliased, null);
	}

	private Account(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.AccountRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.AccountRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_ACCOUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AccountRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_ACCOUNT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AccountRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AccountRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_ACCOUNT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Account as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Account(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Account rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Account(name, null);
	}
}
