/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.AddressRecord> {

	private static final long serialVersionUID = 1137175242;

	/**
	 * The singleton instance of <code>lifetime.address</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Address ADDRESS = new lifetime.backend.persistence.jooq.tables.Address();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.AddressRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.AddressRecord.class;
	}

	/**
	 * The column <code>lifetime.address.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.address.street</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.String> STREET = createField("street", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.address.locality</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.String> LOCALITY = createField("locality", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.address.postal_code</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.String> POSTAL_CODE = createField("postal_code", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>lifetime.address.country</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.String> COUNTRY = createField("country", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * Create a <code>lifetime.address</code> table reference
	 */
	public Address() {
		this("address", null);
	}

	/**
	 * Create an aliased <code>lifetime.address</code> table reference
	 */
	public Address(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Address.ADDRESS);
	}

	private Address(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.AddressRecord> aliased) {
		this(alias, aliased, null);
	}

	private Address(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.AddressRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.AddressRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AddressRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_ADDRESS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AddressRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.AddressRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_ADDRESS_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_ADDRESS_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Address as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Address(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Address rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Address(name, null);
	}
}
