/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lifetime.backend.persistence.jooq.Keys;
import lifetime.backend.persistence.jooq.Lifetime;
import lifetime.backend.persistence.jooq.tables.records.CompetitionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition extends TableImpl<CompetitionRecord> {

    private static final long serialVersionUID = -2015203027;

    /**
     * The reference instance of <code>lifetime.competition</code>
     */
    public static final Competition COMPETITION = new Competition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CompetitionRecord> getRecordType() {
        return CompetitionRecord.class;
    }

    /**
     * The column <code>lifetime.competition.id</code>.
     */
    public final TableField<CompetitionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lifetime.competition.title</code>.
     */
    public final TableField<CompetitionRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>lifetime.competition.performance</code>.
     */
    public final TableField<CompetitionRecord, UInteger> PERFORMANCE = createField("performance", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

    /**
     * The column <code>lifetime.competition.sport_id</code>.
     */
    public final TableField<CompetitionRecord, Integer> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lifetime.competition.sport_lifetime_event_id</code>.
     */
    public final TableField<CompetitionRecord, Integer> SPORT_LIFETIME_EVENT_ID = createField("sport_lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>lifetime.competition</code> table reference
     */
    public Competition() {
        this("competition", null);
    }

    /**
     * Create an aliased <code>lifetime.competition</code> table reference
     */
    public Competition(String alias) {
        this(alias, COMPETITION);
    }

    private Competition(String alias, Table<CompetitionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Competition(String alias, Table<CompetitionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lifetime.LIFETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CompetitionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_COMPETITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CompetitionRecord> getPrimaryKey() {
        return Keys.KEY_COMPETITION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CompetitionRecord>> getKeys() {
        return Arrays.<UniqueKey<CompetitionRecord>>asList(Keys.KEY_COMPETITION_PRIMARY, Keys.KEY_COMPETITION_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CompetitionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CompetitionRecord, ?>>asList(Keys.FK_COMPETITION_SPORT1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Competition as(String alias) {
        return new Competition(alias, this);
    }

    /**
     * Rename this table
     */
    public Competition rename(String name) {
        return new Competition(name, null);
    }
}
