/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Competition extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> {

	private static final long serialVersionUID = 43245444;

	/**
	 * The singleton instance of <code>lifetime.competition</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Competition COMPETITION = new lifetime.backend.persistence.jooq.tables.Competition();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.CompetitionRecord.class;
	}

	/**
	 * The column <code>lifetime.competition.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.competition.title</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.competition.performance</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, org.jooq.types.UInteger> PERFORMANCE = createField("performance", org.jooq.impl.SQLDataType.INTEGERUNSIGNED, this, "");

	/**
	 * The column <code>lifetime.competition.sport_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, java.lang.Integer> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.competition.sport_lifetime_event_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, java.lang.Integer> SPORT_LIFETIME_EVENT_ID = createField("sport_lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.competition</code> table reference
	 */
	public Competition() {
		this("competition", null);
	}

	/**
	 * Create an aliased <code>lifetime.competition</code> table reference
	 */
	public Competition(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Competition.COMPETITION);
	}

	private Competition(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Competition(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_COMPETITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_COMPETITION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_COMPETITION_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_COMPETITION_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_COMPETITION_SPORT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Competition as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Competition(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Competition rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Competition(name, null);
	}
}
