/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Course extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.CourseRecord> {

	private static final long serialVersionUID = -1745412167;

	/**
	 * The singleton instance of <code>lifetime.course</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Course COURSE = new lifetime.backend.persistence.jooq.tables.Course();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.CourseRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.CourseRecord.class;
	}

	/**
	 * The column <code>lifetime.course.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CourseRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.course.name</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CourseRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.course.study_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.CourseRecord, java.lang.Integer> STUDY_ID = createField("study_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.course</code> table reference
	 */
	public Course() {
		this("course", null);
	}

	/**
	 * Create an aliased <code>lifetime.course</code> table reference
	 */
	public Course(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Course.COURSE);
	}

	private Course(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.CourseRecord> aliased) {
		this(alias, aliased, null);
	}

	private Course(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.CourseRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.CourseRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_COURSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CourseRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_COURSE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CourseRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.CourseRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_COURSE_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_COURSE_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.CourseRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.CourseRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_COURSE_STUDY1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Course as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Course(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Course rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Course(name, null);
	}
}
