/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lifetime.backend.persistence.jooq.Keys;
import lifetime.backend.persistence.jooq.Lifetime;
import lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowHowUnit extends TableImpl<KnowHowUnitRecord> {

    private static final long serialVersionUID = -125147465;

    /**
     * The reference instance of <code>lifetime.know_how_unit</code>
     */
    public static final KnowHowUnit KNOW_HOW_UNIT = new KnowHowUnit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KnowHowUnitRecord> getRecordType() {
        return KnowHowUnitRecord.class;
    }

    /**
     * The column <code>lifetime.know_how_unit.id</code>.
     */
    public final TableField<KnowHowUnitRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>lifetime.know_how_unit.title</code>.
     */
    public final TableField<KnowHowUnitRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

    /**
     * The column <code>lifetime.know_how_unit.summary</code>.
     */
    public final TableField<KnowHowUnitRecord, String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>lifetime.know_how_unit.content</code>.
     */
    public final TableField<KnowHowUnitRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

    /**
     * Create a <code>lifetime.know_how_unit</code> table reference
     */
    public KnowHowUnit() {
        this("know_how_unit", null);
    }

    /**
     * Create an aliased <code>lifetime.know_how_unit</code> table reference
     */
    public KnowHowUnit(String alias) {
        this(alias, KNOW_HOW_UNIT);
    }

    private KnowHowUnit(String alias, Table<KnowHowUnitRecord> aliased) {
        this(alias, aliased, null);
    }

    private KnowHowUnit(String alias, Table<KnowHowUnitRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Lifetime.LIFETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<KnowHowUnitRecord, Integer> getIdentity() {
        return Keys.IDENTITY_KNOW_HOW_UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KnowHowUnitRecord> getPrimaryKey() {
        return Keys.KEY_KNOW_HOW_UNIT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KnowHowUnitRecord>> getKeys() {
        return Arrays.<UniqueKey<KnowHowUnitRecord>>asList(Keys.KEY_KNOW_HOW_UNIT_PRIMARY, Keys.KEY_KNOW_HOW_UNIT_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KnowHowUnit as(String alias) {
        return new KnowHowUnit(alias, this);
    }

    /**
     * Rename this table
     */
    public KnowHowUnit rename(String name) {
        return new KnowHowUnit(name, null);
    }
}
