/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowHowUnit extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> {

	private static final long serialVersionUID = 359842385;

	/**
	 * The singleton instance of <code>lifetime.know_how_unit</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.KnowHowUnit KNOW_HOW_UNIT = new lifetime.backend.persistence.jooq.tables.KnowHowUnit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord.class;
	}

	/**
	 * The column <code>lifetime.know_how_unit.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.know_how_unit.title</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>lifetime.know_how_unit.summary</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord, java.lang.String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>lifetime.know_how_unit.content</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.VARCHAR.length(1024), this, "");

	/**
	 * Create a <code>lifetime.know_how_unit</code> table reference
	 */
	public KnowHowUnit() {
		this("know_how_unit", null);
	}

	/**
	 * Create an aliased <code>lifetime.know_how_unit</code> table reference
	 */
	public KnowHowUnit(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT);
	}

	private KnowHowUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> aliased) {
		this(alias, aliased, null);
	}

	private KnowHowUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_KNOW_HOW_UNIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_KNOW_HOW_UNIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_KNOW_HOW_UNIT_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_KNOW_HOW_UNIT_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.KnowHowUnit as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.KnowHowUnit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.KnowHowUnit rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.KnowHowUnit(name, null);
	}
}
