/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowledgeUnit extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord> {

	private static final long serialVersionUID = -947030876;

	/**
	 * The singleton instance of <code>lifetime.knowledge_unit</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.KnowledgeUnit KNOWLEDGE_UNIT = new lifetime.backend.persistence.jooq.tables.KnowledgeUnit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord.class;
	}

	/**
	 * The column <code>lifetime.knowledge_unit.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.knowledge_unit.know_how_unit_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, java.lang.Integer> KNOW_HOW_UNIT_ID = createField("know_how_unit_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.knowledge_unit.lecture_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, java.lang.Integer> LECTURE_ID = createField("lecture_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.knowledge_unit</code> table reference
	 */
	public KnowledgeUnit() {
		this("knowledge_unit", null);
	}

	/**
	 * Create an aliased <code>lifetime.knowledge_unit</code> table reference
	 */
	public KnowledgeUnit(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.KnowledgeUnit.KNOWLEDGE_UNIT);
	}

	private KnowledgeUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord> aliased) {
		this(alias, aliased, null);
	}

	private KnowledgeUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_KNOWLEDGE_UNIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_KNOWLEDGE_UNIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_KNOWLEDGE_UNIT_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_KNOWLEDGE_UNIT_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.KnowledgeUnitRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_KNOWLEDGE_UNIT_KNOW_HOW_UNIT1, lifetime.backend.persistence.jooq.Keys.FK_KNOWLEDGE_UNIT_LECTURE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.KnowledgeUnit as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.KnowledgeUnit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.KnowledgeUnit rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.KnowledgeUnit(name, null);
	}
}
