/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lecture extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.LectureRecord> {

	private static final long serialVersionUID = 1166140796;

	/**
	 * The singleton instance of <code>lifetime.lecture</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Lecture LECTURE = new lifetime.backend.persistence.jooq.tables.Lecture();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.LectureRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.LectureRecord.class;
	}

	/**
	 * The column <code>lifetime.lecture.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LectureRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lecture.title</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LectureRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.lecture.course_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LectureRecord, java.lang.Integer> COURSE_ID = createField("course_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.lecture</code> table reference
	 */
	public Lecture() {
		this("lecture", null);
	}

	/**
	 * Create an aliased <code>lifetime.lecture</code> table reference
	 */
	public Lecture(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Lecture.LECTURE);
	}

	private Lecture(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LectureRecord> aliased) {
		this(alias, aliased, null);
	}

	private Lecture(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LectureRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.LectureRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_LECTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LectureRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_LECTURE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LectureRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LectureRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_LECTURE_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_LECTURE_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LectureRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LectureRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_LECTURE_COURSE1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Lecture as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Lecture(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Lecture rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Lecture(name, null);
	}
}
