/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LifetimeOrg extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord> {

	private static final long serialVersionUID = -1412062809;

	/**
	 * The singleton instance of <code>lifetime.lifetime_org</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.LifetimeOrg LIFETIME_ORG = new lifetime.backend.persistence.jooq.tables.LifetimeOrg();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord.class;
	}

	/**
	 * The column <code>lifetime.lifetime_org.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_org.name</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_org.account_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_org.address_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_org.photo_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.Integer> PHOTO_ID = createField("photo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.lifetime_org</code> table reference
	 */
	public LifetimeOrg() {
		this("lifetime_org", null);
	}

	/**
	 * Create an aliased <code>lifetime.lifetime_org</code> table reference
	 */
	public LifetimeOrg(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.LifetimeOrg.LIFETIME_ORG);
	}

	private LifetimeOrg(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord> aliased) {
		this(alias, aliased, null);
	}

	private LifetimeOrg(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_LIFETIME_ORG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_ORG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_ORG_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_ORG_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LifetimeOrgRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_ORG_ACCOUNT1, lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_ORG_ADDRESS1, lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_ORG_PHOTO1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.LifetimeOrg as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.LifetimeOrg(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.LifetimeOrg rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.LifetimeOrg(name, null);
	}
}
