/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LifetimeUser extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> {

	private static final long serialVersionUID = -242628726;

	/**
	 * The singleton instance of <code>lifetime.lifetime_user</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.LifetimeUser LIFETIME_USER = new lifetime.backend.persistence.jooq.tables.LifetimeUser();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord.class;
	}

	/**
	 * The column <code>lifetime.lifetime_user.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_user.first_name</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.String> FIRST_NAME = createField("first_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_user.last_name</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_user.address_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_user.account_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.lifetime_user.photo_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.Integer> PHOTO_ID = createField("photo_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.lifetime_user</code> table reference
	 */
	public LifetimeUser() {
		this("lifetime_user", null);
	}

	/**
	 * Create an aliased <code>lifetime.lifetime_user</code> table reference
	 */
	public LifetimeUser(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER);
	}

	private LifetimeUser(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> aliased) {
		this(alias, aliased, null);
	}

	private LifetimeUser(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_LIFETIME_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_USER_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_LIFETIME_USER_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_USER_ADDRESS1, lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_USER_ACCOUNT1, lifetime.backend.persistence.jooq.Keys.FK_LIFETIME_USER_PHOTO1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.LifetimeUser as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.LifetimeUser(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.LifetimeUser rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.LifetimeUser(name, null);
	}
}
