/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Project extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.ProjectRecord> {

	private static final long serialVersionUID = -181947435;

	/**
	 * The singleton instance of <code>lifetime.project</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Project PROJECT = new lifetime.backend.persistence.jooq.tables.Project();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.ProjectRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.ProjectRecord.class;
	}

	/**
	 * The column <code>lifetime.project.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.project.title</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.project.summary</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, java.lang.String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>lifetime.project.work_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, java.lang.Integer> WORK_ID = createField("work_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.project</code> table reference
	 */
	public Project() {
		this("project", null);
	}

	/**
	 * Create an aliased <code>lifetime.project</code> table reference
	 */
	public Project(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Project.PROJECT);
	}

	private Project(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.ProjectRecord> aliased) {
		this(alias, aliased, null);
	}

	private Project(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.ProjectRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_PROJECT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.ProjectRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_PROJECT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.ProjectRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.ProjectRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_PROJECT_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_PROJECT_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.ProjectRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_PROJECT_WORK1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Project as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Project(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Project rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Project(name, null);
	}
}
