/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchemaVersion extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord> {

	private static final long serialVersionUID = -487405227;

	/**
	 * The singleton instance of <code>lifetime.schema_version</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.SchemaVersion SCHEMA_VERSION = new lifetime.backend.persistence.jooq.tables.SchemaVersion();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord.class;
	}

	/**
	 * The column <code>lifetime.schema_version.installed_rank</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.Integer> INSTALLED_RANK = createField("installed_rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.version</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>lifetime.schema_version.description</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.type</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.script</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.String> SCRIPT = createField("script", org.jooq.impl.SQLDataType.VARCHAR.length(1000).nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.checksum</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.Integer> CHECKSUM = createField("checksum", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>lifetime.schema_version.installed_by</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.String> INSTALLED_BY = createField("installed_by", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.installed_on</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.sql.Timestamp> INSTALLED_ON = createField("installed_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>lifetime.schema_version.execution_time</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.Integer> EXECUTION_TIME = createField("execution_time", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.schema_version.success</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord, java.lang.Byte> SUCCESS = createField("success", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.schema_version</code> table reference
	 */
	public SchemaVersion() {
		this("schema_version", null);
	}

	/**
	 * Create an aliased <code>lifetime.schema_version</code> table reference
	 */
	public SchemaVersion(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.SchemaVersion.SCHEMA_VERSION);
	}

	private SchemaVersion(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord> aliased) {
		this(alias, aliased, null);
	}

	private SchemaVersion(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_SCHEMA_VERSION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SchemaVersionRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_SCHEMA_VERSION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.SchemaVersion as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.SchemaVersion(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.SchemaVersion rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.SchemaVersion(name, null);
	}
}
