/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sport extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.SportRecord> {

	private static final long serialVersionUID = 1366172829;

	/**
	 * The singleton instance of <code>lifetime.sport</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Sport SPORT = new lifetime.backend.persistence.jooq.tables.Sport();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.SportRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.SportRecord.class;
	}

	/**
	 * The column <code>lifetime.sport.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SportRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.sport.modality</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SportRecord, java.lang.String> MODALITY = createField("modality", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.sport.lifetime_event_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.SportRecord, java.lang.Integer> LIFETIME_EVENT_ID = createField("lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.sport</code> table reference
	 */
	public Sport() {
		this("sport", null);
	}

	/**
	 * Create an aliased <code>lifetime.sport</code> table reference
	 */
	public Sport(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Sport.SPORT);
	}

	private Sport(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.SportRecord> aliased) {
		this(alias, aliased, null);
	}

	private Sport(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.SportRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.SportRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_SPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SportRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_SPORT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SportRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.SportRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_SPORT_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_SPORT_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.SportRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.SportRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_SPORT_LIFETIME_EVENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Sport as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Sport(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Sport rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Sport(name, null);
	}
}
