/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Study extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.StudyRecord> {

	private static final long serialVersionUID = 1495215135;

	/**
	 * The singleton instance of <code>lifetime.study</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Study STUDY = new lifetime.backend.persistence.jooq.tables.Study();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.StudyRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.StudyRecord.class;
	}

	/**
	 * The column <code>lifetime.study.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.StudyRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.study.name</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.StudyRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.study.lifetime_event_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.StudyRecord, java.lang.Integer> LIFETIME_EVENT_ID = createField("lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.study</code> table reference
	 */
	public Study() {
		this("study", null);
	}

	/**
	 * Create an aliased <code>lifetime.study</code> table reference
	 */
	public Study(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Study.STUDY);
	}

	private Study(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.StudyRecord> aliased) {
		this(alias, aliased, null);
	}

	private Study(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.StudyRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.StudyRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_STUDY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.StudyRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_STUDY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.StudyRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.StudyRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_STUDY_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_STUDY_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.StudyRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.StudyRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_STUDY_LIFETIME_EVENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Study as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Study(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Study rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Study(name, null);
	}
}
