/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.TaskRecord> {

	private static final long serialVersionUID = -833639535;

	/**
	 * The singleton instance of <code>lifetime.task</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Task TASK = new lifetime.backend.persistence.jooq.tables.Task();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.TaskRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.TaskRecord.class;
	}

	/**
	 * The column <code>lifetime.task.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TaskRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.task.title</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TaskRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

	/**
	 * The column <code>lifetime.task.summary</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TaskRecord, java.lang.String> SUMMARY = createField("summary", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>lifetime.task.project_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TaskRecord, java.lang.Integer> PROJECT_ID = createField("project_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.task</code> table reference
	 */
	public Task() {
		this("task", null);
	}

	/**
	 * Create an aliased <code>lifetime.task</code> table reference
	 */
	public Task(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Task.TASK);
	}

	private Task(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.TaskRecord> aliased) {
		this(alias, aliased, null);
	}

	private Task(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.TaskRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.TaskRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TaskRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_TASK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TaskRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TaskRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_TASK_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_TASK_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.TaskRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.TaskRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_TASK_PROJECT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Task as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Task(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Task rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Task(name, null);
	}
}
