/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Training extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.TrainingRecord> {

	private static final long serialVersionUID = -1695407966;

	/**
	 * The singleton instance of <code>lifetime.training</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Training TRAINING = new lifetime.backend.persistence.jooq.tables.Training();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.TrainingRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.TrainingRecord.class;
	}

	/**
	 * The column <code>lifetime.training.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.training.type</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>lifetime.training.sport_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, java.lang.Integer> SPORT_ID = createField("sport_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.training.sport_lifetime_event_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, java.lang.Integer> SPORT_LIFETIME_EVENT_ID = createField("sport_lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.training</code> table reference
	 */
	public Training() {
		this("training", null);
	}

	/**
	 * Create an aliased <code>lifetime.training</code> table reference
	 */
	public Training(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Training.TRAINING);
	}

	private Training(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.TrainingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Training(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.TrainingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TrainingRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_TRAINING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TrainingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.TrainingRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_TRAINING_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.TrainingRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_TRAINING_SPORT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Training as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Training(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Training rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Training(name, null);
	}
}
