/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkUnit extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> {

	private static final long serialVersionUID = -1710842781;

	/**
	 * The singleton instance of <code>lifetime.work_unit</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.WorkUnit WORK_UNIT = new lifetime.backend.persistence.jooq.tables.WorkUnit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord.class;
	}

	/**
	 * The column <code>lifetime.work_unit.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.work_unit.know_how_unit_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, java.lang.Integer> KNOW_HOW_UNIT_ID = createField("know_how_unit_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.work_unit.task_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, java.lang.Integer> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.work_unit</code> table reference
	 */
	public WorkUnit() {
		this("work_unit", null);
	}

	/**
	 * Create an aliased <code>lifetime.work_unit</code> table reference
	 */
	public WorkUnit(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT);
	}

	private WorkUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> aliased) {
		this(alias, aliased, null);
	}

	private WorkUnit(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_WORK_UNIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_WORK_UNIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_WORK_UNIT_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_WORK_UNIT_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_WORK_UNIT_KNOW_HOW_UNIT1, lifetime.backend.persistence.jooq.Keys.FK_WORK_UNIT_TASK1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.WorkUnit as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.WorkUnit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.WorkUnit rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.WorkUnit(name, null);
	}
}
