/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Work extends org.jooq.impl.TableImpl<lifetime.backend.persistence.jooq.tables.records.WorkRecord> {

	private static final long serialVersionUID = -1294486662;

	/**
	 * The singleton instance of <code>lifetime.work</code>
	 */
	public static final lifetime.backend.persistence.jooq.tables.Work WORK = new lifetime.backend.persistence.jooq.tables.Work();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<lifetime.backend.persistence.jooq.tables.records.WorkRecord> getRecordType() {
		return lifetime.backend.persistence.jooq.tables.records.WorkRecord.class;
	}

	/**
	 * The column <code>lifetime.work.id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>lifetime.work.workcol</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkRecord, java.lang.String> WORKCOL = createField("workcol", org.jooq.impl.SQLDataType.VARCHAR.length(45), this, "");

	/**
	 * The column <code>lifetime.work.lifetime_event_id</code>.
	 */
	public final org.jooq.TableField<lifetime.backend.persistence.jooq.tables.records.WorkRecord, java.lang.Integer> LIFETIME_EVENT_ID = createField("lifetime_event_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>lifetime.work</code> table reference
	 */
	public Work() {
		this("work", null);
	}

	/**
	 * Create an aliased <code>lifetime.work</code> table reference
	 */
	public Work(java.lang.String alias) {
		this(alias, lifetime.backend.persistence.jooq.tables.Work.WORK);
	}

	private Work(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.WorkRecord> aliased) {
		this(alias, aliased, null);
	}

	private Work(java.lang.String alias, org.jooq.Table<lifetime.backend.persistence.jooq.tables.records.WorkRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, lifetime.backend.persistence.jooq.Lifetime.LIFETIME, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<lifetime.backend.persistence.jooq.tables.records.WorkRecord, java.lang.Integer> getIdentity() {
		return lifetime.backend.persistence.jooq.Keys.IDENTITY_WORK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkRecord> getPrimaryKey() {
		return lifetime.backend.persistence.jooq.Keys.KEY_WORK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<lifetime.backend.persistence.jooq.tables.records.WorkRecord>>asList(lifetime.backend.persistence.jooq.Keys.KEY_WORK_PRIMARY, lifetime.backend.persistence.jooq.Keys.KEY_WORK_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.WorkRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<lifetime.backend.persistence.jooq.tables.records.WorkRecord, ?>>asList(lifetime.backend.persistence.jooq.Keys.FK_WORK_LIFETIME_EVENT1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.tables.Work as(java.lang.String alias) {
		return new lifetime.backend.persistence.jooq.tables.Work(alias, this);
	}

	/**
	 * Rename this table
	 */
	public lifetime.backend.persistence.jooq.tables.Work rename(java.lang.String name) {
		return new lifetime.backend.persistence.jooq.tables.Work(name, null);
	}
}
