/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.AddressRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 861672186;

	/**
	 * Setter for <code>lifetime.address.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.address.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.address.street</code>.
	 */
	public void setStreet(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.address.street</code>.
	 */
	public java.lang.String getStreet() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.address.locality</code>.
	 */
	public void setLocality(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.address.locality</code>.
	 */
	public java.lang.String getLocality() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>lifetime.address.postal_code</code>.
	 */
	public void setPostalCode(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lifetime.address.postal_code</code>.
	 */
	public java.lang.String getPostalCode() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>lifetime.address.country</code>.
	 */
	public void setCountry(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>lifetime.address.country</code>.
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.Address.ADDRESS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.Address.ADDRESS.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return lifetime.backend.persistence.jooq.tables.Address.ADDRESS.LOCALITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return lifetime.backend.persistence.jooq.tables.Address.ADDRESS.POSTAL_CODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return lifetime.backend.persistence.jooq.tables.Address.ADDRESS.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLocality();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPostalCode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value2(java.lang.String value) {
		setStreet(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value3(java.lang.String value) {
		setLocality(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value4(java.lang.String value) {
		setPostalCode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord value5(java.lang.String value) {
		setCountry(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AddressRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AddressRecord
	 */
	public AddressRecord() {
		super(lifetime.backend.persistence.jooq.tables.Address.ADDRESS);
	}

	/**
	 * Create a detached, initialised AddressRecord
	 */
	public AddressRecord(java.lang.Integer id, java.lang.String street, java.lang.String locality, java.lang.String postalCode, java.lang.String country) {
		super(lifetime.backend.persistence.jooq.tables.Address.ADDRESS);

		setValue(0, id);
		setValue(1, street);
		setValue(2, locality);
		setValue(3, postalCode);
		setValue(4, country);
	}
}
