/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CompetitionRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.CompetitionRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 59409306;

	/**
	 * Setter for <code>lifetime.competition.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.competition.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.competition.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.competition.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.competition.performance</code>.
	 */
	public void setPerformance(org.jooq.types.UInteger value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.competition.performance</code>.
	 */
	public org.jooq.types.UInteger getPerformance() {
		return (org.jooq.types.UInteger) getValue(2);
	}

	/**
	 * Setter for <code>lifetime.competition.sport_id</code>.
	 */
	public void setSportId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lifetime.competition.sport_id</code>.
	 */
	public java.lang.Integer getSportId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>lifetime.competition.sport_lifetime_event_id</code>.
	 */
	public void setSportLifetimeEventId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>lifetime.competition.sport_lifetime_event_id</code>.
	 */
	public java.lang.Integer getSportLifetimeEventId() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, org.jooq.types.UInteger, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.Competition.COMPETITION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.Competition.COMPETITION.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field3() {
		return lifetime.backend.persistence.jooq.tables.Competition.COMPETITION.PERFORMANCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return lifetime.backend.persistence.jooq.tables.Competition.COMPETITION.SPORT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return lifetime.backend.persistence.jooq.tables.Competition.COMPETITION.SPORT_LIFETIME_EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value3() {
		return getPerformance();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getSportId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSportLifetimeEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value3(org.jooq.types.UInteger value) {
		setPerformance(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value4(java.lang.Integer value) {
		setSportId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord value5(java.lang.Integer value) {
		setSportLifetimeEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CompetitionRecord values(java.lang.Integer value1, java.lang.String value2, org.jooq.types.UInteger value3, java.lang.Integer value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CompetitionRecord
	 */
	public CompetitionRecord() {
		super(lifetime.backend.persistence.jooq.tables.Competition.COMPETITION);
	}

	/**
	 * Create a detached, initialised CompetitionRecord
	 */
	public CompetitionRecord(java.lang.Integer id, java.lang.String title, org.jooq.types.UInteger performance, java.lang.Integer sportId, java.lang.Integer sportLifetimeEventId) {
		super(lifetime.backend.persistence.jooq.tables.Competition.COMPETITION);

		setValue(0, id);
		setValue(1, title);
		setValue(2, performance);
		setValue(3, sportId);
		setValue(4, sportLifetimeEventId);
	}
}
