/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KnowHowUnitRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.KnowHowUnitRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1367349466;

	/**
	 * Setter for <code>lifetime.know_how_unit.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.know_how_unit.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.know_how_unit.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.know_how_unit.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.know_how_unit.summary</code>.
	 */
	public void setSummary(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.know_how_unit.summary</code>.
	 */
	public java.lang.String getSummary() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>lifetime.know_how_unit.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lifetime.know_how_unit.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT.SUMMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSummary();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KnowHowUnitRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KnowHowUnitRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KnowHowUnitRecord value3(java.lang.String value) {
		setSummary(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KnowHowUnitRecord value4(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public KnowHowUnitRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached KnowHowUnitRecord
	 */
	public KnowHowUnitRecord() {
		super(lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT);
	}

	/**
	 * Create a detached, initialised KnowHowUnitRecord
	 */
	public KnowHowUnitRecord(java.lang.Integer id, java.lang.String title, java.lang.String summary, java.lang.String content) {
		super(lifetime.backend.persistence.jooq.tables.KnowHowUnit.KNOW_HOW_UNIT);

		setValue(0, id);
		setValue(1, title);
		setValue(2, summary);
		setValue(3, content);
	}
}
