/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LifetimeUserRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.LifetimeUserRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -608629995;

	/**
	 * Setter for <code>lifetime.lifetime_user.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.lifetime_user.first_name</code>.
	 */
	public void setFirstName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.first_name</code>.
	 */
	public java.lang.String getFirstName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.lifetime_user.last_name</code>.
	 */
	public void setLastName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.last_name</code>.
	 */
	public java.lang.String getLastName() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>lifetime.lifetime_user.address_id</code>.
	 */
	public void setAddressId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.address_id</code>.
	 */
	public java.lang.Integer getAddressId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>lifetime.lifetime_user.account_id</code>.
	 */
	public void setAccountId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.account_id</code>.
	 */
	public java.lang.Integer getAccountId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>lifetime.lifetime_user.photo_id</code>.
	 */
	public void setPhotoId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_user.photo_id</code>.
	 */
	public java.lang.Integer getPhotoId() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.FIRST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.LAST_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.ACCOUNT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER.PHOTO_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getFirstName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLastName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getAccountId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getPhotoId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value2(java.lang.String value) {
		setFirstName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value3(java.lang.String value) {
		setLastName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value4(java.lang.Integer value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value5(java.lang.Integer value) {
		setAccountId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord value6(java.lang.Integer value) {
		setPhotoId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeUserRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LifetimeUserRecord
	 */
	public LifetimeUserRecord() {
		super(lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER);
	}

	/**
	 * Create a detached, initialised LifetimeUserRecord
	 */
	public LifetimeUserRecord(java.lang.Integer id, java.lang.String firstName, java.lang.String lastName, java.lang.Integer addressId, java.lang.Integer accountId, java.lang.Integer photoId) {
		super(lifetime.backend.persistence.jooq.tables.LifetimeUser.LIFETIME_USER);

		setValue(0, id);
		setValue(1, firstName);
		setValue(2, lastName);
		setValue(3, addressId);
		setValue(4, accountId);
		setValue(5, photoId);
	}
}
