/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LifetimeEventRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.LifetimeEventRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.sql.Date, java.sql.Date, lifetime.backend.persistence.jooq.enums.LifetimeEventStatus, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1890497071;

	/**
	 * Setter for <code>lifetime.lifetime_event.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.event_start</code>.
	 */
	public void setEventStart(java.sql.Date value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.event_start</code>.
	 */
	public java.sql.Date getEventStart() {
		return (java.sql.Date) getValue(2);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.event_end</code>.
	 */
	public void setEventEnd(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.event_end</code>.
	 */
	public java.sql.Date getEventEnd() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.status</code>.
	 */
	public void setStatus(lifetime.backend.persistence.jooq.enums.LifetimeEventStatus value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.status</code>.
	 */
	public lifetime.backend.persistence.jooq.enums.LifetimeEventStatus getStatus() {
		return (lifetime.backend.persistence.jooq.enums.LifetimeEventStatus) getValue(4);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.lifetime_user_id</code>.
	 */
	public void setLifetimeUserId(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.lifetime_user_id</code>.
	 */
	public java.lang.Integer getLifetimeUserId() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.lifetime_org_id</code>.
	 */
	public void setLifetimeOrgId(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.lifetime_org_id</code>.
	 */
	public java.lang.Integer getLifetimeOrgId() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>lifetime.lifetime_event.address_id</code>.
	 */
	public void setAddressId(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>lifetime.lifetime_event.address_id</code>.
	 */
	public java.lang.Integer getAddressId() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.sql.Date, java.sql.Date, lifetime.backend.persistence.jooq.enums.LifetimeEventStatus, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.sql.Date, java.sql.Date, lifetime.backend.persistence.jooq.enums.LifetimeEventStatus, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field3() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.EVENT_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.EVENT_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<lifetime.backend.persistence.jooq.enums.LifetimeEventStatus> field5() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.LIFETIME_USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.LIFETIME_ORG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value3() {
		return getEventStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getEventEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public lifetime.backend.persistence.jooq.enums.LifetimeEventStatus value5() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getLifetimeUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getLifetimeOrgId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value3(java.sql.Date value) {
		setEventStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value4(java.sql.Date value) {
		setEventEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value5(lifetime.backend.persistence.jooq.enums.LifetimeEventStatus value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value6(java.lang.Integer value) {
		setLifetimeUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value7(java.lang.Integer value) {
		setLifetimeOrgId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord value8(java.lang.Integer value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public LifetimeEventRecord values(java.lang.Integer value1, java.lang.String value2, java.sql.Date value3, java.sql.Date value4, lifetime.backend.persistence.jooq.enums.LifetimeEventStatus value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LifetimeEventRecord
	 */
	public LifetimeEventRecord() {
		super(lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT);
	}

	/**
	 * Create a detached, initialised LifetimeEventRecord
	 */
	public LifetimeEventRecord(java.lang.Integer id, java.lang.String title, java.sql.Date eventStart, java.sql.Date eventEnd, lifetime.backend.persistence.jooq.enums.LifetimeEventStatus status, java.lang.Integer lifetimeUserId, java.lang.Integer lifetimeOrgId, java.lang.Integer addressId) {
		super(lifetime.backend.persistence.jooq.tables.LifetimeEvent.LIFETIME_EVENT);

		setValue(0, id);
		setValue(1, title);
		setValue(2, eventStart);
		setValue(3, eventEnd);
		setValue(4, status);
		setValue(5, lifetimeUserId);
		setValue(6, lifetimeOrgId);
		setValue(7, addressId);
	}
}
