/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SportRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.SportRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1389279282;

	/**
	 * Setter for <code>lifetime.sport.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.sport.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.sport.modality</code>.
	 */
	public void setModality(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.sport.modality</code>.
	 */
	public java.lang.String getModality() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.sport.lifetime_event_id</code>.
	 */
	public void setLifetimeEventId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.sport.lifetime_event_id</code>.
	 */
	public java.lang.Integer getLifetimeEventId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.Sport.SPORT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.Sport.SPORT.MODALITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return lifetime.backend.persistence.jooq.tables.Sport.SPORT.LIFETIME_EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getModality();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getLifetimeEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportRecord value2(java.lang.String value) {
		setModality(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportRecord value3(java.lang.Integer value) {
		setLifetimeEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SportRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SportRecord
	 */
	public SportRecord() {
		super(lifetime.backend.persistence.jooq.tables.Sport.SPORT);
	}

	/**
	 * Create a detached, initialised SportRecord
	 */
	public SportRecord(java.lang.Integer id, java.lang.String modality, java.lang.Integer lifetimeEventId) {
		super(lifetime.backend.persistence.jooq.tables.Sport.SPORT);

		setValue(0, id);
		setValue(1, modality);
		setValue(2, lifetimeEventId);
	}
}
