/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.WorkRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -358339414;

	/**
	 * Setter for <code>lifetime.work.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.work.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.work.workcol</code>.
	 */
	public void setWorkcol(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.work.workcol</code>.
	 */
	public java.lang.String getWorkcol() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.work.lifetime_event_id</code>.
	 */
	public void setLifetimeEventId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.work.lifetime_event_id</code>.
	 */
	public java.lang.Integer getLifetimeEventId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.Work.WORK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return lifetime.backend.persistence.jooq.tables.Work.WORK.WORKCOL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return lifetime.backend.persistence.jooq.tables.Work.WORK.LIFETIME_EVENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getWorkcol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getLifetimeEventId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkRecord value2(java.lang.String value) {
		setWorkcol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkRecord value3(java.lang.Integer value) {
		setLifetimeEventId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkRecord
	 */
	public WorkRecord() {
		super(lifetime.backend.persistence.jooq.tables.Work.WORK);
	}

	/**
	 * Create a detached, initialised WorkRecord
	 */
	public WorkRecord(java.lang.Integer id, java.lang.String workcol, java.lang.Integer lifetimeEventId) {
		super(lifetime.backend.persistence.jooq.tables.Work.WORK);

		setValue(0, id);
		setValue(1, workcol);
		setValue(2, lifetimeEventId);
	}
}
