/**
 * This class is generated by jOOQ
 */
package lifetime.backend.persistence.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorkUnitRecord extends org.jooq.impl.UpdatableRecordImpl<lifetime.backend.persistence.jooq.tables.records.WorkUnitRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1948723975;

	/**
	 * Setter for <code>lifetime.work_unit.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>lifetime.work_unit.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>lifetime.work_unit.know_how_unit_id</code>.
	 */
	public void setKnowHowUnitId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>lifetime.work_unit.know_how_unit_id</code>.
	 */
	public java.lang.Integer getKnowHowUnitId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>lifetime.work_unit.task_id</code>.
	 */
	public void setTaskId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>lifetime.work_unit.task_id</code>.
	 */
	public java.lang.Integer getTaskId() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT.KNOW_HOW_UNIT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT.TASK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getKnowHowUnitId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTaskId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkUnitRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkUnitRecord value2(java.lang.Integer value) {
		setKnowHowUnitId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkUnitRecord value3(java.lang.Integer value) {
		setTaskId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public WorkUnitRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached WorkUnitRecord
	 */
	public WorkUnitRecord() {
		super(lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT);
	}

	/**
	 * Create a detached, initialised WorkUnitRecord
	 */
	public WorkUnitRecord(java.lang.Integer id, java.lang.Integer knowHowUnitId, java.lang.Integer taskId) {
		super(lifetime.backend.persistence.jooq.tables.WorkUnit.WORK_UNIT);

		setValue(0, id);
		setValue(1, knowHowUnitId);
		setValue(2, taskId);
	}
}
