/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lifetime.persistence;

import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.commons.lang.RandomStringUtils;

/**
 *
 * @author zua
 */
public class TestHelper {

    public static Integer getRandomId() {
        Logger.getLogger(TestHelper.class.getName()).info("Generating a random ID");
        Integer result = new Random().nextInt();
        Logger.getLogger(TestHelper.class.getName()).info("Generated: " + result);
        return result;
    }

    public static byte[] getRandomByteArray() {
        Logger.getLogger(TestHelper.class.getName()).info("Generating a random byte[]");
        byte[] result = new byte[1024];
        new Random().nextBytes(result);
        Logger.getLogger(TestHelper.class.getName()).log(Level.INFO, "Generated bytes: {0}", result.length);
        return result;
    }

    static String getRandomString() {
        Logger.getLogger(TestHelper.class.getName()).info("Generating a random STRING");
        String result = RandomStringUtils.randomAlphanumeric(20);
        Logger.getLogger(TestHelper.class.getName()).log(Level.INFO, "Generated: {0}", result);
        return result;
    }

}
